

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Iosevka NF"
style = "Bold"

[font.bold_italic]
family = "Iosevka NF"
style = "Bold Italic"

[font.italic]
family = "Iosevka NF"
style = "Italic"

[font.normal]
family = "Consolas"
style = "Regular"

[window]
dynamic_padding = true
dynamic_title = true

[general]
import = ["~/.config/alacritty/colors.toml"]

[window.padding]
x = 5
y = 5
