    [colors.primary]
    background = "#fdf6e3"
    foreground = "#586e75"

    [colors.cursor]
    cursor = "#586e75"
    text = "#fdf6e3"

    [colors.normal]
    black  = "#073642"
    white  = "#eee8d5"
    blue   = "#268bd2"
    cyan   = "#2aa198"
    green  = "#859900"
    magenta= "#d33682"
    red    = "#dc322f"
    yellow = "#b58900"
