[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[colors.cursor]
cursor = "#abb2bf"
text = "#282c34"

[colors.normal]
black  = "#181a1f"
white  = "#fffefe"
blue   = "#61afef"
cyan   = "#56b6c2"
green  = "#98c379"
magenta= "#c678dd"
red    = "#e06c75"
yellow = "#e5c07b"
